version: '3.8'
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
